-- Tabela de Jogos
create table public.games (
  id uuid default gen_random_uuid() primary key,
  title text not null,
  slug text unique not null,
  cover_url text,
  steam_app_id int unique,
  release_date date,
  created_at timestamptz default now() not null
);

-- Tabela de Gêneros
create table public.genres (
  id int generated by default as identity primary key,
  name text not null,
  slug text unique not null
);

-- Tabela Pivô (Jogo <-> Gênero)
create table public.game_genres (
  game_id uuid references public.games(id) on delete cascade not null,
  genre_id int references public.genres(id) on delete cascade not null,
  primary key (game_id, genre_id) -- Chave Composta!
);

create table public.library_items (
  id uuid default gen_random_uuid() primary key,
  user_id uuid references public.profiles(id) on delete cascade not null,
  game_id uuid references public.games(id) on delete restrict not null,
  
  -- Status e Plataforma como Texto (validado via Check Constraint)
  status text not null check (status in ('BACKLOG', 'PLAYING', 'COMPLETED', 'DROPPED', 'WISHLIST')),
  platform text not null check (platform in ('PC', 'PS5', 'PS4', 'XBOX', 'SWITCH', 'MOBILE', 'OTHER')),
  
  playtime_minutes int default 0 check (playtime_minutes >= 0),
  rating int check (rating >= 0 and rating <= 5), -- Nota de 0 a 5
  review text,
  
  started_at date,
  finished_at date,
  updated_at timestamptz default now() not null,
  
  -- Constraints Lógicas
  constraint unique_user_game unique (user_id, game_id), -- Um jogo por usuário
  constraint check_dates_logic check (finished_at >= started_at) -- Não pode zerar antes de começar
);

-- Busca rápida por slug do jogo (para rotas)
create index idx_games_slug on public.games(slug);

-- Listar jogos de um usuário rapidamente
create index idx_library_user on public.library_items(user_id);

-- Filtrar biblioteca por status (ex: "Mostrar só o que estou jogando")
create index idx_library_status on public.library_items(status);